

services:
  mongodb:
    image: mongo:7.0
    container_name: leetcode_mongodb_dev
    restart: always
    ports:
    
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: leetcode_dev
    volumes:
      - mongodb_data:/data/db

  postgresql:
    image: postgres:15-alpine
    container_name: leetcode_postgresql_dev
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: leetcode_analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: leetcode_redis_dev
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  postgresql_data:
  redis_data:
